### ISSUE TITLE
Unable to run example 5

### ISSUE THREAD

**Issue by fatema1804** [CharafeddineMechalikh/PureEdgeSim#10]
Hi, I am working on distributed task offloading approach in which some tasks will execute on the 
cloud and some will execute on Fog/MEC server. so is it possible in Pureedgesim tool? How can I do this?
I have tried to run example 1 and 5 but unable to do so. Other examples are working fine. But for my work I found example 5 is useful that's why I want to run it badly.

Custom Orchestrator- Unknnown orchestration algorithm 'TRADE_OFF', please check the simulation parameters file...

This is the error occured while running example 5

Thanks

**Comment by CharafeddineMechalikh** [comment]
hi,
 yes you can do it using pureEdgeSim.
To do it, you need to extend the orchestrator.class (like example 5)
The algorithm named as "Trade_off" is used by the default orchestrator.
The custom orchestrator used in example 5 doesn't have an algorithm with that name.
 It has another algorithm named "INCEREASE_LIFETIME" ( see CustomEdgeOrchestrator.Java in examples folder)


so to use that algorithm you need to add it to the simulation parameters file (settings/ folder) so the corresponding line will be : 

orchestration_algorithms=INCEREASE_LIFETIME



and then you can run example 1 and 5.


This algorithm will aim to balance and balance the Energy consumption of battery powered devices.
you can implement yours the same way or follow this to implement yours https://drive.google.com/file/d/1Qg7UTop7Wa7TZQ8MOrXZkyo1Rga455Qm/view

**Comment by fatema1804** [comment]
Problem solved.
Thanks.

**Comment by CharafeddineMechalikh** [comment]
great
