### ISSUE TITLE
Orchestrator

### ISSUE THREAD

**Issue by fatema1804** [CharafeddineMechalikh/PureEdgeSim#14]
This whole simulation is mainly based on orchastrator. So can u plz explain what exactly orchastrator is? A device? A software? because I have read whole document but still i didnt understatnd what it actually is. And same for cluster-head also.

**Comment by CharafeddineMechalikh** [comment]
Hi,
The orchestrator could be another device or the same device that is offloading the task.
if you disabled it from simulation_parameters.prop, it means that the each devices will chose the offlaoding desitnation according to its own perspective. You can also set another device to be the orchestrator (for example a base station/ fog server) or just another edge device.

In example 6, the edge devices were grouped into clusters, in which the head of each cluster was responsible for orchestrating the tasks for the other devices. Check example 6 for more details.

When you add your custom tasks orchestration/ load balancing algorithm, follow example 5. it shows how to create a custom orchestrator. The algorithm is added there (in the custom orchestrator class).
__________________________
if you set the option enable_orchestrator=true and set its deployment location to the cloud for example, the offloading request will be sent to the cloud, the cloud will choose the offloading destination and offlaods that task. after the execution, the results will be returned to the cloud, and then to the device.
if you disable that option, the task will be directly offloaded to the destination, and the results will be directly returned to the device.

of course, you can use any device. no only the cloud.
_________________________
in mobile edge computing scenarios, if you want your offlaoding decisiions to be made on the mobile devices, just leave that option disabled or select the deployement to the EDGE. it is the same thing.
this way the device selects the base station that best suits its requiremnts, or selects the cloud.

if you want the decisions to be made on the base stations, you need to deploy the orchestrator to the FOG. this way, the offlaoding request will be sent to the nearest base station, the base station will decide if the task should be executed locally, or on another base station, or on the cloud.


so it depends on your scenario.


Hopefully, this answers you question.
