### ISSUE TITLE
data placment

### ISSUE THREAD

**Issue by itafarin** [CharafeddineMechalikh/PureEdgeSim#19]
Where I can Add my  Data Placement Algorithm

**Comment by CharafeddineMechalikh** [comment]
Hello, sorry for the delay,
in this simulator data is modeled as "tasks". and I usually refer to "placement algorithm" as orchestration algorithm. THe class reponsible for this is the Orchestrator class. You can implement your algorithm by creating a custom orchestrator (or modifying an existing one). This custom orchestrator has to extend the orchestrator.java class.
Examples 5 and 8 show how to create a custom orchestrator. In exemple 8, a fuzzy logic based placement/orchestration algorithm is used. I encourage you to take a look at these examples, and the other ones as well.
If you have any other questions, let me know. (for faster reponse, you can contact me through my email address, see the read me file).

**Comment by itafarin** [comment]
Hello, thank you for your answer
I will read the examples and use your tips by email
Thanks alot

**Comment by CharafeddineMechalikh** [comment]
Always welcome. Feel free to ask any questions.
