### ISSUE TITLE
how can i build my own scenario?

### ISSUE THREAD

**Issue by zhanglintao819** [CharafeddineMechalikh/PureEdgeSim#2]

**Comment by CharafeddineMechalikh** [comment]
Hello, i'm working on it. give me a week and i will provide a detailed description starting from now.
I was working on an improved version.
See you in a while mate

**Comment by zhanglintao819** [comment]
I am looking forward that.&nbsp; thank you very much

---Original---

**Comment by CharafeddineMechalikh** [comment]
You're welcome

**Comment by CharafeddineMechalikh** [comment]
Hi,
I added some simple examples under the example folder, 
You can start by trying them. 
Will add more soon.
Thank you

**Comment by zhanglintao819** [comment]
thank you .&nbsp; but I find that import this version will cause some problems. I can not solve it



---Original---

**Comment by CharafeddineMechalikh** [comment]
Hi again, 
Don't import the project.
On eclipse click on new-> new java project-> use default location-> chose where the simulator is located.

After that it will take one or two minutes to download dependencies. 

Then you can use it. 
(see the Gif i provided in the readme file) 
Thank you.

**Comment by DongDongJu** [comment]
I solved the dependencies problem but this repo don't have any scenario examples? I want to check the running status. So, If you possible then, can you add the example with the scenarios? Making the scenarios looks so difficult for starting people.

**Comment by CharafeddineMechalikh** [comment]
Yes , indeed there was an issue (package naming), now it is fixed,you can try again with the latest version
