### ISSUE TITLE
Project Errors/Warnings

### ISSUE THREAD

**Issue by SuperLuigiLinked** [CharafeddineMechalikh/PureEdgeSim#20]
After I download the project and the libraries, I still have a couple errors and warnings.
Is there anything I can do to fix them?

Here's a picture showing the errors:
![image](https://user-images.githubusercontent.com/65352263/84822282-6d595300-afea-11ea-959a-b992acb5ab28.png)

**Comment by CharafeddineMechalikh** [comment]
Hi, 
Yes the error happended to me as well when I tried to redownload it from github.
I have uploaded a newer version.
You should redownload it again,
and please follow these steps here:
https://github.com/CharafeddineMechalikh/PureEdgeSim/wiki/Downloading-and-Running-PureEdgeSim-for-the-First-Time
