### ISSUE TITLE
Energy and latency optimization

### ISSUE THREAD

**Issue by abhishekraj95** [CharafeddineMechalikh/PureEdgeSim#21]
Is there a method by which I can directly optimize energy and latency for my scenario in the simulator. What are the factors I need to consider and what changes I can make in the current examples to create my own scenario to obtain optimization??

**Comment by CharafeddineMechalikh** [comment]
Hi, 
yes you can optimize energy and latency.
To do so first, you need to create your custom orchestrator class (you can follow example 5 and 8).
A basic orchestration algorithm is given in example 5 and a more complex Fuzzy Logic based algorithm is given in example 8.
make sure to read them and to try them.
You can follow example 7 as well to learn how to add your custom input files and ouput path.

In example 8, the latency is minimized. You can add energy  as well. For example, by avoiding battery-powered devices, or by choosing a the offloading destination that consumes less energy, etc...
If the default energy model does not meet your needs, you can always extend it and add your custom one.  Example 3 shows how to do this.

I hope that I have answered your questions, and waiting for your feedback.
I can help you further if I know a little more about your scenario.
If I did not respond quickly, you can contact me on my email, see the readme file.
kind regards.
