### ISSUE TITLE
I want to export the workload

### ISSUE THREAD

**Issue by qjncn** [CharafeddineMechalikh/PureEdgeSim#22]
I want to export the workload, do time series prediction with MATLAB, and then write the program to the data center to save energy. 
Can you export the workload, or get a stable workload data set like the PlanetLab or Google data set in CloudSimPlus?
thank you .

**Comment by ZahraSf** [comment]
I did it by modifying DefaultTaskGenerator class and creating my CustomTaskGenerator. I counted all tasks in each timeslot and saved the results in a CSV file.
