### ISSUE TITLE
Run the code in Server

### ISSUE THREAD

**Issue by anirudhajitani** [CharafeddineMechalikh/PureEdgeSim#23]
Hi,
Could you provide instructions to compile and run any of the examples/code in server without Eclipse through command line?

**Comment by CharafeddineMechalikh** [comment]
hello,
Assuming that git and maven are already installed, PureEdgeSim can be run from the command line as follows:
1.	First, the project source code must be downloaded by cloning the repository using the command  “git clone https://github.com/CharafeddineMechalikh/PureEdgeSim.git”. 
2.	Now that the project is cloned, it can be built using Maven by executing the “mvn clean install” command in the directory where it was cloned.
3.	Now, the examples can be executed, on windows, linux, or Mac operating systems, using the command “mvn exec:java -Dexec.mainClass="package.Class_Name"”. For instance, to execute “Example1”, the command will be  “mvn exec:java -Dexec.mainClass="examples.Example1"”.
