### ISSUE TITLE
Number of Failed Tasks show Negative

### ISSUE THREAD

**Issue by oumermuhammed** [CharafeddineMechalikh/PureEdgeSim#32]
When generating a "Tasks successfully executed result in the case of SimulationParameters is choosen all " it shows the algorithms a negative number of tasks failed. No code is modified in both algorithms.
![image](https://user-images.githubusercontent.com/33282861/177936440-e80b1df6-5487-42ef-b57f-5d631c9b7970.png)
Why is it?

**Comment by CharafeddineMechalikh** [comment]
Hi,
thanks for the feedback,
I will check that.
