### ISSUE TITLE
“The import 'net' cannot be resolvable.” when run the "import net.sourceforge.jFuzzyLogic.FIS" in example 8.

### ISSUE THREAD

**Issue by anonymity1** [CharafeddineMechalikh/PureEdgeSim#35]
Hi,
I am running the project via Eclipse IDE and everything ran well.
However, an error occurred when I ran example 8.

![image](https://user-images.githubusercontent.com/58590304/188304840-68430119-6de8-4248-aae7-e135be775595.png)
![image](https://user-images.githubusercontent.com/58590304/188304855-f29faef5-0783-43b9-a7e8-34b3aea4a860.png)
How can I solve this problem?

**Comment by CharafeddineMechalikh** [comment]
Hi,
you need to add the corresponding library to the BUILD path.
You can find the library inside Lib/ folder
