### ISSUE TITLE
Unable to configure Project

### ISSUE THREAD

**Issue by chetanbulla** [CharafeddineMechalikh/PureEdgeSim#5]
Dear Sir,
I have installed PureEdgeSim as per the instruction given . It is showing lot of errors . PLease let me know how to resolve these errors

**Comment by CharafeddineMechalikh** [comment]
hello, 
I update the readme file just now,
After adding PureEdgeSim, it should automotically download the required libraries (see the gifin the readme, where the errors disappear withing 1 or two minutes, just after downloading the required libraries)
if the errors persist, this means that maven (which download the libraries for you) is not installed on your IDE. so there are two options, either to add maven to your IDE (eclipse for example) or to manually add the required libraries. I uploaded the libraries needed, you download them from here  :
https://drive.google.com/open?id=1tc3_1UnIYO0AtAXDVf18AHj5g8MdFMNs

to add them to the project follow this  :    
 https://www.wikihow.com/Add-JARs-to-Project-Build-Paths-in-Eclipse-(Java)

after that the errors will disappear and you can run the examples, and build your own scenario.

thanks for yout feedback.
it the errors persist, do not hesitate and contact me.
