### ISSUE TITLE
main.java File is not available 

### ISSUE THREAD

**Issue by muneeb666** [CharafeddineMechalikh/PureEdgeSim#6]
hi, 

Main .java  class is not available in the current version in the package. But it was available in the previous PureEdgeSim version 2.0.0. But when I download this, I couldn't see it in any of the package. 

It is showing the mainapplication.java class but not the main.java class. 

Also, there are some errors in each package. I have even sent an email. Kindly have a look and please guide me. Thank you

**Comment by CharafeddineMechalikh** [comment]
Hello, 
tha main.java clas has been renamed to MainApplication.java
you can launch the simulation by executing the MainApplication.java or by creating your own Class (see the examples on how to create your own class) 
The benefit of creating your own class is the abitlity to use custom models and classes (see the examples) like a custom mobility model, a custom edge orchestrator (i.e. a custom load balancing/ tasks orchestration algorithm, a custom energy model....etc). 
you can also do that (use your custom models ..) by editing the MainApplication class. However, i do not advise you to do it as it contains many lines of code. Unlike when you create your own class (one line to load your model) and one line to launch the simulation ( see the examples for more details).

when you add PureEdgeSim to your IDE (for example eclipse) , it will download the required libraries. While downloading them, some errors will appear in the code. These errors will disappear after one minute or two, when the required libraries are downloaded.

If the errors persist, this means that maven is not installed on your IDE. You have then two options. you can download the libraries manually from here :
https://drive.google.com/open?id=1tc3_1UnIYO0AtAXDVf18AHj5g8MdFMNs
And add them to your project (manually) as in this tutorial :    
 https://www.wikihow.com/Add-JARs-to-Project-Build-Paths-in-Eclipse-(Java)

or, you can add maven to your IDE.and it will automatically download the libraries.

Once the libraries are added,  the errors will disappear and you can run the examples, and build your own scenario.

thanks for yout feedback.
it the errors persist, do not hesitate and contact me.
