### ISSUE TITLE
can i change the speed that follow a distribution like possion?

### ISSUE THREAD

**Issue by zhanglintao819** [CharafeddineMechalikh/PureEdgeSim#7]

**Comment by CharafeddineMechalikh** [comment]
You can do that programmaticaly, you need to build your custom mobility model, which is not that hard.
In a example 2 you can find a custom mobility model you can edit that class (CustomMobilityModel.class) or create a new one by following it (you must extend the MobilityModel when creating a new one) 

Then you can do whatever you want 

Execute example 2 to see the difference.

Waiting for your feedback, I can provide a step by step tutorial if you want
